export const siteConfig = {
  name: "AutoTrader Bot — AI-Powered DeFi on HashKey Chain",
  shortName: "AutoTrader",
  description:
    "AI-gated autonomous trading on HashKey Chain. The bot consults your chosen LLM (GPT-4, Claude, 100+ models via OpenRouter) before every on-chain execution — combining 4/4 technical signal validation with deep AI risk analysis for institutional-grade DeFi automation.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://autotrader-bot.dev",
  keywords: [
    "ai-gated defi trading",
    "hashkey chain",
    "autonomous trading bot",
    "llm trading agent",
    "on-chain ai execution",
    "openrouter trading",
    "gpt-4 defi",
    "claude trading ai",
    "multi-model strategy analyst",
    "hsk token",
    "pretrade risk validation",
    "ai trade decision log",
    "onchain horizon hackathon",
    "defi ai agent",
  ],
  judgingHighlights: [
    "AI-gated execution: every trade must pass both 4/4 technical signals AND LLM risk analysis before on-chain execution",
    "Multi-provider AI: users bring their own API key — OpenRouter (100+ models), OpenAI, Anthropic",
    "Full AI decision log: every analysis, confidence score, and reasoning persisted for audit trail",
    "One-shot AI execution: analyze + decide + execute on HashKey Chain in a single flow",
    "AI auto-trade mode: autonomous scanning + AI gate + on-chain execution loop",
    "AES-256 encrypted key storage — user API keys never leave the backend unencrypted",
    "PostgreSQL + Prisma persistence with full migration support",
    "Deployed on HashKey Chain testnet with verified Solidity contract",
  ],
};
