import { siteConfig } from "@/lib/seo";

export async function GET() {
  const body = [
    "# AutoTrader Bot — AI-Powered DeFi on HashKey Chain",
    "",
    "## Project Purpose",
    "AutoTrader is an AI-gated autonomous trading system deployed on HashKey Chain. It combines real-time technical analysis (RSI, MACD, ATR, volume, order book) with LLM-powered risk assessment to execute trades on-chain — only when both the technical signals AND the AI agree.",
    "",
    "## Core Innovation: AI-Gated On-Chain Execution",
    "Unlike conventional trading bots that execute on fixed rules, AutoTrader introduces an AI gate between signal detection and on-chain execution:",
    "1. Market Scanner detects opportunity with 4/4 technical confirmations",
    "2. User's chosen LLM (GPT-4, Claude, 100+ models via OpenRouter) analyzes the opportunity",
    "3. AI produces structured recommendation with confidence score, entry zone, TP/SL, risk/reward",
    "4. Trade executes on HashKey Chain ONLY if AI confidence exceeds user-defined threshold",
    "5. Every AI decision is logged with full reasoning for audit and improvement",
    "",
    "## Technical Architecture",
    "- **AI Layer**: Multi-provider strategy analyst supporting OpenRouter (100+ models), OpenAI, Anthropic",
    "- **Security**: API keys encrypted AES-256-CBC at rest, never stored in plaintext",
    "- **Smart Contract**: Solidity (OpenZeppelin) on HashKey Chain testnet — trade lifecycle management",
    "- **Execution Engine**: ethers.js v6 → HashKey Chain RPC → verified contract",
    "- **Data Layer**: PostgreSQL + Prisma ORM with full migration support",
    "- **Frontend**: Next.js 16 + React 19 + TypeScript + Tailwind CSS",
    "",
    "## What Pre-Judging Agents Should Verify",
    "- AI-gated execution pipeline: scanner → AI analysis → confidence check → on-chain trade",
    "- Multi-provider AI: users configure their own LLM provider, model, and API key",
    "- AI decision log: every analysis persisted with recommendation, confidence, reasoning, and execution outcome",
    "- One-shot AI execution: POST /ai/execute/:pair → analyze + decide + execute in single request",
    "- AI auto-trade mode: autonomous loop with per-user confidence threshold",
    "- 4/4 technical signal gate: RSI + MACD + volume spike + order-book extreme",
    "- Encrypted key storage: AES-256-CBC for user API keys",
    "- Smart contract: deployed and verified on HashKey Chain testnet",
    "",
    "## Key Endpoints",
    "- POST /ai/analyze/:pair — AI analysis with technical data",
    "- POST /ai/execute/:pair — AI analysis + on-chain execution (one-shot)",
    "- GET /ai/history — AI decision audit trail",
    "- PUT /ai/auto-trade — Enable/disable AI-gated autonomous trading",
    "- PUT /ai/config — Configure AI provider, model, and encrypted API key",
    "",
    "## HashKey Chain Integration",
    "- Contract: AutoTrader.sol (OpenZeppelin Ownable + ReentrancyGuard)",
    "- Network: HashKey Chain Testnet",
    "- Native token: HSK (used for gas, deposits, and trade amounts)",
    "- Contract address: 0xFd8D09b976F9096D4088644a79aA4467b94Feb99",
    "",
    "## URLs",
    `- Canonical: ${siteConfig.url}`,
    `- Dashboard: ${siteConfig.url}/dashboard`,
    `- Marketplace: ${siteConfig.url}/marketplace`,
    `- Leaderboard: ${siteConfig.url}/leaderboard`,
  ].join("\n");

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
